"use strict";
document.addEventListener("DOMContentLoaded", () => {
 if (window.timelineGameV2Loaded) return;
 window.timelineGameV2Loaded = true;
 const enhancedGame = document.createElement("script");
 enhancedGame.src = "./js/timeline-game.js?v=email-otp-20260915-4";
 enhancedGame.onload = () => document.dispatchEvent(new Event("DOMContentLoaded"));
 document.head.append(enhancedGame);
 return;
 const host=window.location.hostname==="127.0.0.1"?"127.0.0.1":"localhost",API=`${window.GamingSession.apiOrigin}/api/v1`,track=document.querySelector("#timeline-track"),cards=document.querySelector("#timeline-cards"),submit=document.querySelector("#timeline-submit"),next=document.querySelector("#timeline-next"),status=document.querySelector("#timeline-status"),score=document.querySelector("#timeline-score"),progress=document.querySelector("#timeline-progress"),result=document.querySelector("#timeline-result");let daily,roundIndex=0,placing=[];
 const api=async(path,options={})=>{const response=await window.GamingSession.fetch(`${API}${path}`,{credentials:"include",headers:{"Content-Type":"application/json"},...options}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message||"The timeline could not be reached.");return body.data;};
 const card=(event,placed=false)=>`<article class="timeline-event-card ${placed?"is-placed":""}" draggable="${placed?"false":"true"}" data-event-id="${event.id}"><span>${event.category}</span><h3>${event.title}</h3><p>${event.description}</p></article>`;
 const render=()=>{const round=daily.rounds[roundIndex],events=[...round.events].sort(()=>Math.random()-.5);placing=[];result.hidden=true;next.hidden=true;submit.hidden=false;submit.disabled=true;document.querySelector("#timeline-category").textContent=[...new Set(round.events.map(e=>e.category))].join(" / ");progress.textContent=`ROUND ${roundIndex+1} OF ${daily.roundsTotal}`;status.textContent="Drag an event onto a point. Cards alternate above and below the line.";track.innerHTML=[0,1,2,3].map(i=>`<div class="timeline-slot ${i%2===0?"is-top":"is-bottom"}" data-slot="${i}"><span class="timeline-node">${i+1}</span><div class="timeline-drop">DROP EVENT</div></div>`).join("");cards.innerHTML=events.map(e=>card(e)).join("");bind();};
 const bind=()=>{document.querySelectorAll(".timeline-event-card[draggable='true']").forEach(el=>el.addEventListener("dragstart",e=>{e.dataTransfer.setData("text/plain",el.dataset.eventId);el.classList.add("is-dragging");}));document.querySelectorAll(".timeline-event-card").forEach(el=>el.addEventListener("dragend",()=>el.classList.remove("is-dragging")));document.querySelectorAll(".timeline-slot").forEach(slot=>{slot.addEventListener("dragover",e=>{e.preventDefault();slot.classList.add("is-over");});slot.addEventListener("dragleave",()=>slot.classList.remove("is-over"));slot.addEventListener("drop",e=>{e.preventDefault();slot.classList.remove("is-over");const id=e.dataTransfer.getData("text/plain"),event=daily.rounds[roundIndex].events.find(x=>x.id===id),i=Number(slot.dataset.slot);if(!event||placing[i])return;placing[i]=event;slot.querySelector(".timeline-drop").outerHTML=card(event,true);cards.querySelector(`[data-event-id="${id}"]`)?.remove();submit.disabled=placing.filter(Boolean).length!==4;});});};
 const load=async()=>{try{const user=await api("/users/me");document.querySelector("#timeline-player-name").textContent=`@${(user.user||user).username}`;daily=await api("/timeline/daily");score.textContent=`${daily.totalScore} / 200 XP`;roundIndex=daily.rounds.findIndex(r=>!r.completed);if(roundIndex<0){progress.textContent="DAILY COMPLETE";status.textContent="You have completed all five rounds. Return tomorrow for fresh events.";return;}render();}catch(error){status.textContent=error.message==="Authentication required."?"Sign in from the home page to start Timeline.":error.message;}};
 submit.addEventListener("click",async()=>{if(placing.filter(Boolean).length!==4)return;submit.disabled=true;try{const out=await api(`/timeline/daily/rounds/${roundIndex}`,{method:"POST",body:JSON.stringify({eventIds:placing.map(e=>e.id)})});daily.totalScore+=out.xpEarned;score.textContent=`${daily.totalScore} / 200 XP`;status.textContent=`${out.correctPositions} of 4 positions correct.`;result.hidden=false;result.innerHTML=`<span>ROUND ANALYSIS</span><h2>+${out.xpEarned} XP</h2><p>${out.correctPositions} correctly placed. True order:</p><ol>${out.solution.map(e=>`<li><strong>${e.date}</strong> ${e.title}</li>`).join("")}</ol>`;submit.hidden=true;if(out.dailyComplete){progress.textContent="DAILY COMPLETE";status.textContent="All five rounds complete. A fresh timeline arrives tomorrow.";}else next.hidden=false;}catch(error){status.textContent=error.message;submit.disabled=false;}});next.addEventListener("click",()=>{daily.rounds[roundIndex].completed=true;roundIndex+=1;render();});load();
});
